const API='https://api.github.com';
const CONTRIBUTIONS_API='https://github-contributions-api.jogruber.de/v4';
const $=s=>document.querySelector(s);
const views={search:$('#searchView'),loading:$('#loadingView'),profile:$('#profileView'),error:$('#errorView')};
let data=null, period='week', avatarDataUrl=null;
function show(name){Object.entries(views).forEach(([k,v])=>v.classList.toggle('hidden',k!==name));window.scrollTo(0,0)}
function sinceFor(p){const d=new Date();const ms={day:864e5,week:7*864e5,month:30*864e5,sixmonths:182*864e5,year:365*864e5};return p==='lifetime'?new Date(0):new Date(d-ms[p])}
function fmt(n){return new Intl.NumberFormat().format(n||0)}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function api(path){const r=await fetch(API+path,{headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2026-03-10'}});if(!r.ok)throw new Error(r.status===404?'User not found.':r.status===403?'GitHub API is temporarily rate limited. Please try again shortly.':`GitHub API error (${r.status}).`);return r.json()}
async function contributions(username){const r=await fetch(`${CONTRIBUTIONS_API}/${encodeURIComponent(username)}?y=all`);if(!r.ok)throw new Error('Could not load the GitHub contribution graph.');return r.json()}
function parseInput(value){let v=value.trim().replace(/^@/,'');if(/^https?:\/\//i.test(v)||/^github\.com\//i.test(v)){const u=new URL(/^https?:\/\//i.test(v)?v:`https://${v}`);if(u.hostname.toLowerCase()!=='github.com')throw new Error('Please enter a github.com profile link.');v=u.pathname.split('/').filter(Boolean)[0]||''}if(!/^[a-zA-Z0-9-]+$/.test(v))throw new Error('Enter a GitHub username or profile link.');return v}
async function load(input){show('loading');$('#loadingText').textContent='Finding your profile...';try{const username=parseInput(input);const user=await api(`/users/${encodeURIComponent(username)}`);$('#loadingText').textContent='Loading repositories...';const repos=[];for(let page=1;page<=3;page++){const batch=await api(`/users/${encodeURIComponent(username)}/repos?per_page=100&page=${page}&type=owner&sort=pushed`);repos.push(...batch);if(batch.length<100)break}$('#loadingText').textContent='Loading contributions...';let contributionData={total:{},contributions:[]};try{contributionData=await contributions(user.login)}catch(e){console.warn(e)}data={user,repos,contributionData};await applyTheme(user.avatar_url);render();show('profile');location.hash='/'+encodeURIComponent(user.login)}catch(e){$('#errorText').textContent=e.message;show('error')}}
function contributionMap(){return new Map((data.contributionData.contributions||[]).map(x=>[x.date,x]))}
function contributionCount(p){const start=sinceFor(p),end=new Date();return(data.contributionData.contributions||[]).filter(x=>{const d=new Date(`${x.date}T23:59:59`);return d>=start&&d<=end}).reduce((n,x)=>n+x.count,0)}
function yearlyTotal(){return Object.values(data.contributionData.total||{}).reduce((n,x)=>n+Number(x||0),0)}
function periodLabel(){return{day:'Last 24 hours',week:'Last 7 days',month:'Last month',sixmonths:'Last 6 months',year:'Last year',lifetime:'All time'}[period]}
function lifeStats(){const u=data.user;return{repos:u.public_repos,followers:u.followers,following:u.following,stars:data.repos.reduce((a,r)=>a+(r.stargazers_count||0),0)}}
async function applyTheme(url){try{const img=new Image();img.crossOrigin='anonymous';img.src=url;await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject});const c=document.createElement('canvas'),ctx=c.getContext('2d',{willReadFrequently:true});c.width=48;c.height=48;ctx.drawImage(img,0,0,48,48);const px=ctx.getImageData(0,0,48,48).data,bins=new Map();for(let i=0;i<px.length;i+=16){const q=rgbToHsl(px[i],px[i+1],px[i+2]);if(q.l<.12||q.l>.9||q.s<.25)continue;const key=Math.round(q.h*24)/24;bins.set(key,(bins.get(key)||0)+q.s*(.4+q.l)*100)}let hue=.25,best=-1;for(const [h,score] of bins){if(score>best){best=score;hue=Number(h)}}document.documentElement.style.setProperty('--accent',hsl(hue,.9,.62));document.documentElement.style.setProperty('--accent2',hsl(hue,.75,.72));document.documentElement.style.setProperty('--bg',hsl(hue,.22,.045));document.documentElement.style.setProperty('--panel',hsl(hue,.18,.075));document.documentElement.style.setProperty('--panel2',hsl(hue,.18,.105));document.documentElement.style.setProperty('--line',hsl(hue,.16,.16));document.documentElement.style.setProperty('--level1',hsl(hue,.48,.22));document.documentElement.style.setProperty('--level2',hsl(hue,.62,.34));document.documentElement.style.setProperty('--level3',hsl(hue,.72,.48));avatarDataUrl=await imageToDataUrl(img)}catch(e){console.warn('Could not extract avatar colors; using default theme.',e)}}
function rgbToHsl(r,g,b){r/=255;g/=255;b/=255;const max=Math.max(r,g,b),min=Math.min(r,g,b);let h=0,s=0;const l=(max+min)/2;if(max!==min){const d=max-min;s=l>.5?d/(2-max-min):d/(max+min);switch(max){case r:h=(g-b)/d+(g<b?6:0);break;case g:h=(b-r)/d+2;break;default:h=(r-g)/d+4}h/=6}return{h,s,l}}
function hsl(h,s,l){return`hsl(${Math.round(h*360)} ${Math.round(s*100)}% ${Math.round(l*100)}%)`}
async function imageToDataUrl(img){const c=document.createElement('canvas');c.width=img.naturalWidth||img.width;c.height=img.naturalHeight||img.height;c.getContext('2d').drawImage(img,0,0);return c.toDataURL('image/png')}
function render(){const u=data.user;$('#avatar').src=u.avatar_url;$('#displayName').textContent=u.name||u.login;$('#handle').textContent='@'+u.login+(u.bio?' · '+u.bio:'');$('#githubProfile').href=u.html_url;renderStats();renderCalendar();renderRepos()}
function renderStats(){const count=contributionCount(period),life=lifeStats();$('#periodLabel').textContent=periodLabel().toUpperCase();const cards=period==='lifetime'?[['CONTRIBUTIONS',yearlyTotal(),'total GitHub contributions'],['PUBLIC REPOS',life.repos,'public repositories'],['STARS',life.stars,'stars in loaded repos'],['FOLLOWERS',life.followers,'people following you']]:[['CONTRIBUTIONS',count,'GitHub contribution activity'],['ACTIVE DAYS',activeDays(period),'days with activity'],['BEST DAY',bestDay(period),'contributions in one day'],['LONGEST STREAK',longestStreak(period),'consecutive active days']];$('#statsGrid').innerHTML=cards.map(c=>`<div class="stat"><div class="label">${c[0]}</div><div class="value">${typeof c[1]==='number'?fmt(c[1]):esc(c[1])}</div><div class="note">${c[2]}</div></div>`).join('');const extras=period==='lifetime'?[['ACCOUNT AGE',age(data.user.created_at)],['FOLLOWING',life.following],['TOP REPO',topRepoName()]]:[['PUBLIC REPOSITORIES',life.repos],['FOLLOWERS',life.followers],['TOTAL CONTRIBUTIONS',yearlyTotal()]];$('#extraStats').innerHTML=extras.map(x=>`<div class="extra"><b>${typeof x[1]==='number'?fmt(x[1]):esc(x[1])}</b><span>${x[0]}</span></div>`).join('');document.querySelectorAll('.periods button').forEach(b=>b.classList.toggle('active',b.dataset.period===period))}
function periodItems(p){const start=sinceFor(p);return(data.contributionData.contributions||[]).filter(x=>new Date(`${x.date}T23:59:59`)>=start)}
function activeDays(p){return periodItems(p).filter(x=>x.count>0).length}
function bestDay(p){return periodItems(p).reduce((m,x)=>Math.max(m,x.count),0)}
function longestStreak(p){const arr=periodItems(p).sort((a,b)=>a.date.localeCompare(b.date));let best=0,run=0,prev=null;for(const x of arr){const d=new Date(`${x.date}T00:00:00`);const contiguous=prev&&Math.round((d-prev)/864e5)===1;if(x.count>0)run=contiguous?run+1:1;else run=0;best=Math.max(best,run);prev=d}return best}
function age(s){return`${((Date.now()-new Date(s))/31557600000).toFixed(1)} years`}
function topRepoName(){return[...data.repos].sort((a,b)=>(b.stargazers_count||0)-(a.stargazers_count||0))[0]?.name||'—'}
function renderCalendar(){const map=contributionMap(),graph=$('#contributionGraph');graph.innerHTML='';const end=new Date();end.setHours(23,59,59,999);const start=new Date(end);start.setDate(start.getDate()-364);start.setDate(start.getDate()-start.getDay());const days=[];for(let i=0;i<371;i++){const d=new Date(start);d.setDate(start.getDate()+i);if(d>end)break;const key=d.toISOString().slice(0,10),item=map.get(key)||{count:0,level:0};days.push({date:key,...item})}const weeks=Math.ceil(days.length/7);graph.style.gridTemplateColumns=`repeat(${weeks},1fr)`;days.forEach(x=>{const cell=document.createElement('span');cell.className=`contrib-cell level-${x.level}`;cell.title=`${x.count} contribution${x.count===1?'':'s'} · ${x.date}`;graph.appendChild(cell)});$('#calendarTotal').textContent=`${fmt(contributionCount('year'))} contributions in the last year`}
function renderRepos(){const rs=[...data.repos].sort((a,b)=>(b.stargazers_count||0)-(a.stargazers_count||0)).slice(0,6);$('#repos').innerHTML=rs.length?rs.map(r=>`<article class="repo"><div class="repo-top"><a class="repo-name" href="${r.html_url}" target="_blank" rel="noreferrer">${esc(r.name)}</a><span class="repo-count">★ ${fmt(r.stargazers_count)}</span></div><div class="repo-desc">${esc(r.description||'No description')}</div><div class="repo-meta"><span>${esc(r.language||'Unknown')}</span><span>Forks <b>${fmt(r.forks_count)}</b></span><span>Issues <b>${fmt(r.open_issues_count)}</b></span></div></article>`).join(''):'<div class="stats-message">No public repositories found.</div>'}
function selectedModules(){return Object.fromEntries([...document.querySelectorAll('[data-module]')].map(x=>[x.dataset.module,x.checked]))}
function buildShareCalendar(){const map=contributionMap(),end=new Date();end.setHours(23,59,59,999);const anchor=new Date(end);anchor.setDate(anchor.getDate()-182);anchor.setDate(anchor.getDate()-anchor.getDay());const days=[];for(let i=0;i<189;i++){const d=new Date(anchor);d.setDate(anchor.getDate()+i);if(d>end)break;const x=map.get(d.toISOString().slice(0,10))||{level:0};days.push(`<i class="level-${x.level}"></i>`)}return days.join('')}
function updateShareCard(){const m=selectedModules(),u=data.user,count=contributionCount(period),life=lifeStats(),streak=longestStreak(period);let html='';if(m.profile)html+=`<div class="share-profile"><div class="share-avatar-ring">${avatarDataUrl?`<img src="${avatarDataUrl}" alt="">`:''}</div><div><div class="share-kicker">GITBRAG</div><div class="share-name">${esc(u.name||u.login)}</div><div class="share-handle">@${esc(u.login)}</div></div></div>`;if(m.headline)html+=`<div class="share-headline"><div class="share-period">${periodLabel().toUpperCase()}<strong>${fmt(period==='lifetime'?yearlyTotal():count)}</strong><span>CONTRIBUTIONS</span></div><div class="share-bigword">BUILD.<br>SHIP.<br>REPEAT.</div></div>`;if(m.stats)html+=`<div class="share-stats"><div><b>${fmt(life.repos)}</b><span>PUBLIC REPOS</span></div><div><b>${fmt(life.stars)}</b><span>STARS</span></div><div><b>${fmt(life.followers)}</b><span>FOLLOWERS</span></div><div><b>${fmt(streak)}</b><span>LONGEST STREAK</span></div></div>`;if(m.calendar)html+=`<div class="share-section"><div class="share-section-head"><span>CONTRIBUTION ACTIVITY</span><small>LAST 6 MONTHS</small></div><div class="share-calendar">${buildShareCalendar()}</div></div>`;if(m.repos)html+=`<div class="share-section"><div class="share-section-head"><span>TOP REPOSITORIES</span><small>BY STARS</small></div><div class="share-repos">${[...data.repos].sort((a,b)=>(b.stargazers_count||0)-(a.stargazers_count||0)).slice(0,4).map(r=>`<div><b>${esc(r.name)}</b><span>★ ${fmt(r.stargazers_count)} · ${esc(r.language||'Unknown')}</span></div>`).join('')}</div></div>`;if(m.branding)html+=`<div class="share-brand">GIT<span>BRAG</span> · github.com/${esc(u.login)}</div>`;$('#shareCard').innerHTML=html}
function updateSharePreview(){const preview=$('#sharePreview');preview.innerHTML='';const clone=$('#shareCard').cloneNode(true);clone.removeAttribute('id');clone.classList.add('preview-card');preview.appendChild(clone)}
function openPng(){updateShareCard();$('#pngModal').classList.remove('hidden');$('#pngModal').setAttribute('aria-hidden','false');updateSharePreview()}
function closePng(){$('#pngModal').classList.add('hidden');$('#pngModal').setAttribute('aria-hidden','true')}
async function downloadPng(){updateShareCard();const card=$('#shareCard');card.classList.add('rendering');try{const canvas=await html2canvas(card,{backgroundColor:null,scale:2,useCORS:true,logging:false});const link=document.createElement('a');link.download=`${data.user.login}-gitbrag.png`;link.href=canvas.toDataURL('image/png');link.click()}catch(e){alert('Could not create the PNG in this browser. Try again in Chromium or Firefox.');console.error(e)}finally{card.classList.remove('rendering')}}
$('#searchForm').addEventListener('submit',e=>{e.preventDefault();const value=$('#username').value.trim();if(value)load(value)});$('#backBtn').onclick=()=>show('search');$('#errorBack').onclick=()=>show('search');$('.periods').addEventListener('click',e=>{if(e.target.matches('button[data-period]')){period=e.target.dataset.period;renderStats();renderCalendar()}});$('#shareBtn').onclick=()=>{const url=location.href.split('#')[0]+'#/'+encodeURIComponent(data.user.login);if(navigator.share)navigator.share({title:`${data.user.login} on Gitbrag`,url}).catch(()=>{});else navigator.clipboard?.writeText(url)};$('#pngBtn').onclick=openPng;$('#closePng').onclick=closePng;$('.modal-backdrop').onclick=closePng;$('#downloadPng').onclick=downloadPng;document.querySelectorAll('[data-module]').forEach(x=>x.addEventListener('change',()=>{updateShareCard();updateSharePreview()}));const hash=location.hash.match(/^#\/(.+)$/);if(hash)load(decodeURIComponent(hash[1]));
